name: Unit Tests

on:
  [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ./back-end

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install packages
        run: ls

      # - name: Set up Ruby
      #   uses: ruby/setup-ruby@v1
      #   with:
      #     ruby-version: .ruby-version
      #     bundler-cache: true

      # - name: Install dependencies
      #   run: gem install bundler && bundle install

      # - name: Create database
      #   run: bin/rails db:create RAILS_ENV=test
      #        bin/rails db:migrate RAILS_ENV=test

      # - name: Run tests
      #   run: bundle exec rspec
