name: Rails rspecs

on:
  pull_request: # Runs on all pull requests (any base branch)
  push:
    branches:
      - main # Runs only when pushing to main

jobs:
  back-end:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back-end

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y build-essential git libpq-dev libyaml-dev pkg-config

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4.4
          bundler-cache: true

      - name: Install dependencies
        run: gem install bundler && bundle install

      - name: Create database
        env:
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_PORT: 5432
          RAILS_ENV: test
        run: |
          bundle exec rails db:create
          bundle exec rails db:migrate

      - name: Run tests
        env:
          DB_HOST: localhost
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_PORT: 5432
          RAILS_ENV: test
        run: bundle exec rspec
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3

  # 2. Deploy only when on main AND CI passes
  deploy:
    runs-on: ubuntu-latest
    needs: back-end
    if: github.ref == 'refs/heads/main'
    permissions:
      deployments: write
    steps:
      - uses: JorgeLNJunior/render-deploy@v1.4.5
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          github_deployment: true
          deployment_environment: "production"
          github_token: ${{ secrets.GITHUB_TOKEN }}
