name: RuboCop

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: back-end
    env:
      BUNDLE_ONLY: rubocop

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.4.4
        bundler-cache: true

    - name: Install dependencies
      run: gem install bundler && bundle install

    - name: Run RuboCop
      run: bundle exec rubocop --parallel
